### ISSUE TITLE
cargBags?

### ISSUE THREAD

**Issue by ghost** [Phanx/BindsWhen#1]
Is it possible for this to work with cargBagNivaya?

http://www.wowinterface.com/downloads/info22329-cargBagsNivayaRealUIstandalone.html

**Comment by Phanx** [comment]
Please grab the BindsWhen.lua file from the repository and replace the one in your addon folder. Let me know if it works or not, and if Bugger/BugSack/Swatter report any errors if not.

**Comment by ghost** [comment]
No errors with BugSack and BugGrabber enabled. I even disabled all addons except those two, BindsWhen, cargBags and AddoncontrolPanel. Nothing being displayed.

**Comment by Phanx** [comment]
Note that this support **will not** work with cargBags Nivaya at present because the layout does not provide any global access to the cargBags API. The layout author will need to add the following line to their TOC file:

```
## X-cargBags: cargBags
```

You can add this line yourself (and then restart WoW) in the meantime.

**Comment by Phanx** [comment]
The TOC field value is no longer important, `## X-cargBags: NyanCats` will work just as well if the layout author prefers something other than `cargBags`.
