### ISSUE TITLE
Add support for ElvUI

### ISSUE THREAD

**Issue by willgk** [Phanx/BindsWhen#4]
Hi,

Bind's When? Doesn't work with ElvUI (TukUI is the Base Code for this AddOn Set). You can download ElvUI from www.elvui.org or www.tukui.org under the Downloads section.

**Comment by Phanx** [comment]
Please test the latest version from GitHub (just save the .lua file over the one in your AddOns folder) and let me know what happens.

If it doesn't work, please [provide detailed information](http://phanx.net/addons/help#report).
