### ISSUE TITLE
Doesn't work with Combuctor  -.-

### ISSUE THREAD

**Issue by y368413** [Phanx/BindsWhen#5]
What a pity,
Please fix it for all combutor user
http://www.curse.com/addons/wow/combuctor

please again

**Comment by Phanx** [comment]
Please test the latest version from GitHub (just save the .lua file over the one in your AddOns folder) and let me know what happens.

If it doesn't work, please [provide detailed information](http://phanx.net/addons/help#report).

**Comment by y368413** [comment]
Work！Special thanks...
